// src/components/skills/skillsKeyboardData.js

export const KEYBOARD_SKILLS = [
  {
    id: "react",
    label: "React",
    color: "#61dafb",
    title: "React",
    level: "Advanced",
    desc: "Component architecture, state management, routing, reusable UI systems.",
    highlights: ["Hooks", "Reusable components", "Performance mindset"],
  },
  {
    id: "tailwind",
    label: "Tailwind",
    color: "#38bdf8",
    title: "Tailwind CSS",
    level: "Advanced",
    desc: "Modern responsive UI with consistent design tokens and clean layouts.",
    highlights: ["Responsive design", "Design systems", "Fast iteration"],
  },
  {
    id: "vue",
    label: "Vue",
    color: "#42b883",
    title: "Vue.js",
    level: "Intermediate",
    desc: "Component-driven UI and app flows from internship projects.",
    highlights: ["Composition/Options", "Quasar exposure", "Forms + UX"],
  },
  {
    id: "playwright",
    label: "Playwright",
    color: "#a855f7",
    title: "Playwright",
    level: "Intermediate",
    desc: "Automated end-to-end tests for client-side features and flows.",
    highlights: ["E2E testing", "Selectors", "Test stability"],
  },
  {
    id: "spring",
    label: "Spring",
    color: "#22c55e",
    title: "Spring Boot",
    level: "Intermediate",
    desc: "Backend API integration and full-stack app collaboration.",
    highlights: ["REST APIs", "Auth flows", "DB integration"],
  },
  {
    id: "java",
    label: "Java",
    color: "#f59e0b",
    title: "Java",
    level: "Intermediate",
    desc: "Object-oriented programming and backend fundamentals.",
    highlights: ["OOP", "API work", "Clean code basics"],
  },
  {
    id: "python",
    label: "Python",
    color: "#60a5fa",
    title: "Python",
    level: "Intermediate",
    desc: "Used for ML/CV work, prototyping, and practical scripting.",
    highlights: ["Automation", "ML basics", "Prototyping"],
  },
  {
    id: "opencv",
    label: "OpenCV",
    color: "#ef4444",
    title: "OpenCV",
    level: "Intermediate",
    desc: "Image processing pipeline work for academic ML/CV projects.",
    highlights: ["Preprocessing", "Segmentation concepts", "Vision workflows"],
  },
  {
    id: "sql",
    label: "SQL",
    color: "#94a3b8",
    title: "SQL / MySQL",
    level: "Intermediate",
    desc: "Queries, relational thinking, backend integrations.",
    highlights: ["CRUD", "Joins", "Schema awareness"],
  },
];
